CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       TEXT        NOT NULL,
    password    TEXT        NOT NULL, -- BCrypt hash, never plain text
    username    TEXT        NOT NULL,
    full_name   TEXT        NOT NULL,
    address     TEXT,
    gender      TEXT,
    is_enabled  BOOLEAN     NOT NULL DEFAULT TRUE,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL,
    created_by  TEXT        NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    updated_by  TEXT        NOT NULL
);

-- Email and username must be unique among users that are not soft-deleted
CREATE UNIQUE INDEX ux_users_email_active    ON users (email)    WHERE is_deleted = FALSE;
CREATE UNIQUE INDEX ux_users_username_active ON users (username) WHERE is_deleted = FALSE;
