CREATE TABLE orders (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id          BIGINT      NOT NULL REFERENCES users (id),
    invoice_number    TEXT        NOT NULL,
    item_name         TEXT        NOT NULL,
    quantity          BIGINT      NOT NULL,
    item_price        BIGINT      NOT NULL,
    total_price       BIGINT      NOT NULL,
    order_description TEXT,
    order_receive     BOOLEAN     NOT NULL DEFAULT FALSE,
    order_status      TEXT        NOT NULL DEFAULT 'PENDING',
    created_by        TEXT        NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL, -- stored as UTC (+0)
    updated_by        TEXT        NOT NULL,
    updated_at        TIMESTAMPTZ NOT NULL, -- stored as UTC (+0)

    CONSTRAINT ck_orders_quantity     CHECK (quantity > 0),
    CONSTRAINT ck_orders_item_price   CHECK (item_price >= 0),
    CONSTRAINT ck_orders_total_price  CHECK (total_price = quantity * item_price),
    CONSTRAINT ck_orders_order_status CHECK (order_status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED'))
);

CREATE UNIQUE INDEX ux_orders_invoice_number ON orders (invoice_number);
CREATE INDEX ix_orders_users_id ON orders (users_id);
