-- One row per (report request, order status). A report request creates two rows:
-- one for COMPLETED orders and one for IN_PROGRESS orders of the user.
CREATE TABLE report_orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL REFERENCES users (id),
    created_by      TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL, -- stored as UTC (+0)
    updated_by      TEXT        NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL, -- stored as UTC (+0)
    order_status    TEXT        NOT NULL,
    total_amount    BIGINT,               -- sum of orders.total_price, NULL until the AI process finishes
    report_progress TEXT        NOT NULL DEFAULT 'IN_PROGRESS',

    CONSTRAINT ck_report_orders_order_status    CHECK (order_status IN ('COMPLETED', 'IN_PROGRESS')),
    CONSTRAINT ck_report_orders_total_amount    CHECK (total_amount >= 0),
    CONSTRAINT ck_report_orders_report_progress CHECK (report_progress IN ('IN_PROGRESS', 'COMPLETED', 'FAILED'))
);

CREATE INDEX ix_report_orders_user_id ON report_orders (user_id);
