-- One row per JWT access token issued by POST /api/auth/login.
-- A token is only accepted while revoked = FALSE, expired = FALSE and expires_at is in the future.
-- Logout, a new login of the same user, and passing the expiry time all set revoked = TRUE and expired = TRUE.
CREATE TABLE tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users (id),
    token       TEXT        NOT NULL,             -- the signed JWT sent in "Authorization: Bearer <token>"
    expires_at  TIMESTAMPTZ NOT NULL,             -- same instant as the JWT "exp" claim, stored as UTC (+0)
    expired     BOOLEAN     NOT NULL DEFAULT FALSE,
    revoked     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_by  TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,             -- stored as UTC (+0)
    updated_by  TEXT        NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL              -- stored as UTC (+0)
);

CREATE UNIQUE INDEX ux_tokens_token ON tokens (token);
CREATE INDEX ix_tokens_user_id ON tokens (user_id);
-- Used by the job that marks tokens past their expiry as expired and revoked
CREATE INDEX ix_tokens_expires_at_active ON tokens (expires_at) WHERE expired = FALSE OR revoked = FALSE;
