package com.course.springlearning.report.ai;

import com.course.springlearning.order.entity.Order;
import com.course.springlearning.order.entity.OrderStatus;
import com.course.springlearning.order.repository.OrderRepository;
import com.course.springlearning.report.pdf.OrderPdfReportGenerator;
import com.course.springlearning.report.pdf.OrderPdfReportGenerator.GeneratedPdf;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Tools the AI can call while building one report.
 * A new instance is created per report and is bound to one user, so the AI can only read that user's orders.
 * Every result is recorded so the AI's final answer can be checked against the real database values,
 * and the generated PDF files are kept here for the caller to store.
 */
public class OrderReportTools {

    private static final Logger log = LoggerFactory.getLogger(OrderReportTools.class);

    private final OrderRepository orderRepository;
    private final OrderPdfReportGenerator pdfGenerator;
    private final Long userId;
    private final String userFullName;
    private final Map<OrderStatus, Long> totals = new ConcurrentHashMap<>();
    private final Map<OrderStatus, GeneratedPdf> pdfs = new ConcurrentHashMap<>();

    public OrderReportTools(OrderRepository orderRepository, OrderPdfReportGenerator pdfGenerator,
                            Long userId, String userFullName) {
        this.orderRepository = orderRepository;
        this.pdfGenerator = pdfGenerator;
        this.userId = userId;
        this.userFullName = userFullName;
    }

    @Tool(description = "Calculates the total amount of the user's orders with the given order status: "
            + "the sum of total_price of those orders. Returns 0 when the user has no such orders.")
    public long sumOrderTotalPrice(
            @ToolParam(description = "Order status to sum, either COMPLETED or IN_PROGRESS") String orderStatus) {
        OrderStatus status = parseStatus(orderStatus);
        long total = orderRepository.sumTotalPriceByUserIdAndOrderStatus(userId, status.name());
        totals.put(status, total);
        log.info("Tool sumOrderTotalPrice(userId={}, orderStatus={}) = {}", userId, status, total);
        return total;
    }

    @Tool(description = "Generates the PDF report of the user's orders with the given order status. "
            + "The PDF lists every order with its item price, quantity and total price, and the total of all orders. "
            + "Returns a short confirmation with the number of orders and the total of all orders in the PDF.")
    public String generateOrderPdfReport(
            @ToolParam(description = "Order status of the report, either COMPLETED or IN_PROGRESS") String orderStatus) {
        OrderStatus status = parseStatus(orderStatus);
        List<Order> orders = orderRepository.findAllByUser_IdAndOrderStatusOrderByIdAsc(userId, status);
        GeneratedPdf pdf = pdfGenerator.generate(userId, userFullName, status, orders,
                Instant.now().truncatedTo(ChronoUnit.SECONDS));
        pdfs.put(status, pdf);
        log.info("Tool generateOrderPdfReport(userId={}, orderStatus={}): {} orders, total {}, {} bytes",
                userId, status, pdf.orderCount(), pdf.totalAllOrders(), pdf.content().length);
        return "PDF report generated for " + status + " orders: " + pdf.orderCount()
                + " orders, total of all orders " + pdf.totalAllOrders();
    }

    /** What each sumOrderTotalPrice call returned, by order status. */
    public Map<OrderStatus, Long> totals() {
        return Map.copyOf(totals);
    }

    /** The PDF generated by generateOrderPdfReport, by order status. */
    public Map<OrderStatus, GeneratedPdf> pdfs() {
        return Map.copyOf(pdfs);
    }

    // The error message is sent back to the AI, so it can retry with a valid status
    private static OrderStatus parseStatus(String orderStatus) {
        String normalized = orderStatus == null ? "" : orderStatus.trim().toUpperCase(Locale.ROOT);
        return switch (normalized) {
            case "COMPLETED" -> OrderStatus.COMPLETED;
            case "IN_PROGRESS" -> OrderStatus.IN_PROGRESS;
            default -> throw new IllegalArgumentException(
                    "Invalid orderStatus '" + orderStatus + "', use COMPLETED or IN_PROGRESS");
        };
    }
}
